---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-deploy-228
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline-app-228
  replicas: 2 
  template:
    metadata:
      labels:
        app: pipeline-app-228
    spec:
      containers:
      - name: pipelines-javascript-k8s
        image: ezlee/pipelines-javascript-k8s:228
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-service
spec:
  selector:
    app: pipeline-app-228
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-pipeline-app
  namespace: default 
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
  - host: "apps.my-azure.online"
    http:
      paths:
      - path: /app1
        pathType: Prefix
        backend:
          service: 
            name: pipeline-service 
            port: 
              number: 8080 
